# Generated by Django 4.0.3 on 2022-04-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abex', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_of_service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='abex.typeofservice'),
        ),
    ]
