# Generated by Django 4.0.3 on 2022-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abex', '0003_typeofservice_remove_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofservice',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
