# Generated by Django 4.0.3 on 2022-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abex', '0004_alter_typeofservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('accrual', 'Accrual'), ('write-off', 'Write-off')], default='Accrual', max_length=15),
        ),
    ]
