# Generated by Django 4.0.3 on 2022-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abex', '0005_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
